"""Writes the obfuscated TMDB key header.

Borrowed from Reroll, which does the same thing for the same reason. The key
is not a secret worth protecting - TMDB's non-commercial terms let an open
source app ship one, it is read-only, rate-limited and revocable - but a
plaintext string in the binary is handed to anyone who runs `strings` on it
without even looking. This is a speed bump, not encryption.

The generated header is gitignored. Run this once after cloning, or whenever
the key changes.
"""

import getpass
import os
import random

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET_PATH = os.path.join(REPO_ROOT, "include", "Config", "ApiKeys.h")
KEY_FILE_PATH = os.path.join(REPO_ROOT, "tmdb_key.txt")
SUBTITLE_KEY_FILE_PATH = os.path.join(REPO_ROOT, "opensubtitles_key.txt")


def to_c_array(data):
    return ", ".join(f"0x{b:02x}" for b in data)


def read_key():
    # tmdb_key.txt is how this project carried the key before, so an existing
    # one is used rather than asking again for something already on disk.
    if os.path.exists(KEY_FILE_PATH):
        with open(KEY_FILE_PATH, "r", encoding="utf-8") as f:
            existing = f.read().strip()
        if existing:
            print(f"Using the key already in {os.path.basename(KEY_FILE_PATH)}.")
            return existing

    return getpass.getpass(
        "Paste your TMDB API Read Access Token or v3 API key: ").strip()


def read_subtitle_key():
    if os.path.exists(SUBTITLE_KEY_FILE_PATH):
        with open(SUBTITLE_KEY_FILE_PATH, "r", encoding="utf-8") as f:
            existing = f.read().strip()
        if existing:
            print("Using the key already in "
                  f"{os.path.basename(SUBTITLE_KEY_FILE_PATH)}.")
            return existing

    try:
        return input("Paste your opensubtitles.com API key, "
                     "or press Enter to skip: ").strip()
    except EOFError:
        return ""


def obfuscate(key):
    key_bytes = key.encode("utf-8")
    mask = bytes(random.randint(1, 255) for _ in range(16))
    hidden = bytes(b ^ mask[i % 16] for i, b in enumerate(key_bytes))

    decoded = bytes(hidden[i] ^ mask[i % 16] for i in range(len(hidden)))
    assert decoded == key_bytes, "round-trip mismatch, aborting"
    return mask, hidden


def block(name, key):
    mask, hidden = obfuscate(key)
    return (f"inline constexpr unsigned char {name}Mask[] = "
            f"{{ {to_c_array(mask)} }};\n"
            f"inline constexpr unsigned char {name}Obfuscated[] = "
            f"{{ {to_c_array(hidden)} }};\n"
            f"inline constexpr std::size_t {name}Length = "
            f"sizeof({name}Obfuscated);\n")


def empty(name):
    # One byte rather than none: a zero-length array does not compile, and
    # the length below is what says there is no key.
    return (f"inline constexpr unsigned char {name}Mask[] = {{ 0x00 }};\n"
            f"inline constexpr unsigned char {name}Obfuscated[] = {{ 0x00 }};\n"
            f"inline constexpr std::size_t {name}Length = 0;\n")


def main():
    key = read_key()
    if not key:
        raise SystemExit("No key entered, aborting.")

    subtitle_key = read_subtitle_key()

    body = block("TmdbApiKey", key)
    body += (block("OpenSubtitlesApiKey", subtitle_key) if subtitle_key
             else empty("OpenSubtitlesApiKey"))

    content = f'''#pragma once

// Generated by scripts/generate_api_key.py. Do not edit, and do not commit.

#include <cstddef>

namespace Makimedia::Config
{{
{body}}}
'''

    os.makedirs(os.path.dirname(TARGET_PATH), exist_ok=True)
    with open(TARGET_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wrote {TARGET_PATH} ({len(key.encode('utf-8'))}-byte TMDB key, "
          + ("with" if subtitle_key else "no")
          + " opensubtitles key, obfuscated).")


if __name__ == "__main__":
    main()
